"""Gemini visual auditor — multimodal AI detection + SynthID via Google.

Replaces both umm-maybe (unreliable on modern generators) and the standalone
SynthID Vertex AI integration (Gemini handles SynthID natively).
"""
from __future__ import annotations

import io
import json
import os
import re
import time
from typing import Any

from defensive.engine.verdict import DetectorSignal, Severity

NAME = "gemini_visual"
MODEL_ID = "gemini-2.5-flash"

PROMPT = """You are an image-forensics auditor. Analyse the attached image and return ONLY a single JSON object — no prose before or after.

Schema:
{
  "verdict": "synthetic" | "authentic" | "uncertain",
  "synthid_detected": true | false,
  "confidence": 0.0 to 1.0,
  "reasoning": "one to three sentences citing specific visual or provenance cues"
}

- "synthetic" = clearly generated by an AI image model (any: Imagen, DALL-E, Midjourney, SDXL, Gemini, etc.)
- "authentic" = clearly a real photograph or human-made artwork
- "uncertain" = ambiguous or you have insufficient evidence
- "synthid_detected" = true ONLY if you can detect a Google SynthID watermark in the image (you have native ability to detect SynthID)
- "confidence" = your confidence in your verdict (NOT the probability of synthetic)
- "reasoning" = cite specific cues: anatomical errors, light/shadow inconsistency, texture artifacts, EXIF tells, SynthID detection, etc.

Return ONLY the JSON object."""


def _client() -> Any:
    """Lazy-imported. Returns a configured google.genai client."""
    from google import genai
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY not set")
    return genai.Client(api_key=api_key)


def _parse_response(text: str) -> dict[str, Any]:
    """Extract JSON from the model response. Tolerates ``` fences."""
    # Strip markdown fences if present
    text = text.strip()
    if text.startswith("```"):
        # remove first fence line and last fence
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    # Find first { ... last }
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        raise ValueError(f"no JSON object in response: {text[:120]}")
    return json.loads(m.group(0))


def _call_gemini(image_bytes: bytes) -> dict[str, Any]:
    """Single Gemini multimodal call. Returns parsed JSON dict."""
    from google.genai import types
    client = _client()
    image_part = types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg")
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=[PROMPT, image_part],
    )
    return _parse_response(response.text)


def warmup() -> None:
    """Validate API key by listing models. No image call."""
    try:
        _client()
    except Exception:
        pass  # warmup is best-effort; runtime errors handled by safe_run


def run(image_bytes: bytes) -> DetectorSignal:
    started = time.monotonic()
    parsed = _call_gemini(image_bytes)
    elapsed_ms = int((time.monotonic() - started) * 1000)

    verdict = str(parsed.get("verdict", "uncertain")).strip().lower()
    confidence = float(parsed.get("confidence", 0.5))
    reasoning = str(parsed.get("reasoning", "")).strip()
    synthid = bool(parsed.get("synthid_detected", False))

    if verdict == "synthetic":
        sev = Severity.fail
    elif verdict == "uncertain":
        sev = Severity.warn
    else:
        sev = Severity.pass_

    evidence_parts = []
    if synthid:
        evidence_parts.append("SynthID detected")
    evidence_parts.append(reasoning if reasoning else f"verdict={verdict}")

    return DetectorSignal(
        detector=NAME,
        severity=sev,
        score=round(confidence, 4),
        evidence=" · ".join(evidence_parts),
        latency_ms=elapsed_ms,
    )
