"""OpenAI vision auditor — multimodal AI-detection peer to gemini_visual.

Calls GPT-4o (default) to audit an image and decide synthetic / authentic /
uncertain. Output schema mirrors gemini_visual exactly so the composite
engine can treat the two visual auditors symmetrically — when one is fooled
by a same-family generation (Gemini missing its own outputs, OpenAI missing
gpt-image-1 outputs) the other is more likely to catch it.
"""
from __future__ import annotations

import base64
import json
import os
import re
import time
from typing import Any

from defensive.engine.verdict import DetectorSignal, Severity

NAME = "openai_visual"
MODEL_ID = os.environ.get("OPENAI_VISUAL_MODEL", "gpt-4o")

PROMPT = """You are an image-forensics auditor. Analyse the attached image and return ONLY a single JSON object — no prose before or after.

Schema:
{
  "verdict": "synthetic" | "authentic" | "uncertain",
  "confidence": 0.0 to 1.0,
  "reasoning": "one to three sentences citing specific visual or provenance cues"
}

- "synthetic" = clearly generated by an AI image model (any: Imagen, DALL-E, gpt-image, Midjourney, SDXL, Gemini, Flux, etc.)
- "authentic" = clearly a real photograph or human-made artwork
- "uncertain" = ambiguous or you have insufficient evidence
- "confidence" = your confidence in your verdict (NOT the probability of synthetic)
- "reasoning" = cite specific cues: anatomical errors, light/shadow inconsistency, texture artifacts, EXIF tells, telltale generative-model signatures, etc.

Return ONLY the JSON object."""


def _client() -> Any:
    """Lazy-imported OpenAI client."""
    from openai import OpenAI
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not set")
    return OpenAI(api_key=api_key)


def _parse_response(text: str) -> dict[str, Any]:
    """Extract JSON from the model response. Tolerates ``` fences."""
    text = (text or "").strip()
    if text.startswith("```"):
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        raise ValueError(f"no JSON object in response: {text[:120]}")
    return json.loads(m.group(0))


def _call_openai(image_bytes: bytes, mime_type: str = "image/jpeg") -> dict[str, Any]:
    """Single GPT-4o vision call. Returns parsed JSON dict."""
    client = _client()
    b64 = base64.b64encode(image_bytes).decode("ascii")
    data_url = f"data:{mime_type};base64,{b64}"
    resp = client.chat.completions.create(
        model=MODEL_ID,
        temperature=0,
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": PROMPT},
                    {"type": "image_url", "image_url": {"url": data_url}},
                ],
            }
        ],
    )
    return _parse_response(resp.choices[0].message.content or "")


def warmup() -> None:
    """Validate API key without an image call. Best-effort."""
    try:
        _client()
    except Exception:
        pass


def run(image_bytes: bytes, *, mime_type: str = "image/jpeg") -> DetectorSignal:
    started = time.monotonic()
    parsed = _call_openai(image_bytes, mime_type=mime_type)
    elapsed_ms = int((time.monotonic() - started) * 1000)

    verdict = str(parsed.get("verdict", "uncertain")).strip().lower()
    confidence = float(parsed.get("confidence", 0.5))
    reasoning = str(parsed.get("reasoning", "")).strip()

    if verdict == "synthetic":
        sev = Severity.fail
    elif verdict == "uncertain":
        sev = Severity.warn
    else:
        sev = Severity.pass_

    evidence = reasoning if reasoning else f"verdict={verdict}"
    return DetectorSignal(
        detector=NAME,
        severity=sev,
        score=round(confidence, 4),
        evidence=evidence,
        latency_ms=elapsed_ms,
    )
