import "server-only";
import { mkdir, writeFile, rename } from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { listChannels } from "@/lib/foundry";
import { revalidatePath } from "next/cache";

const REPO_ROOT = path.resolve(
  process.env.MENDACITY_REPO_ROOT ||
    path.join(process.env.HOME || "", "Mendacity"),
);
const INBOX = path.join(REPO_ROOT, "missions/inbox");

const MID_RE = /^[A-Za-z0-9][A-Za-z0-9_\-]{0,63}$/;

type Input = {
  missionId?: string;
  operator?: string;
  targetChannel?: string;
  audienceProfile?: string;
  personaArchetype?: string;
  personaNameSeed?: string;
  artifactPrompt?: string;
  dryRun?: boolean;
};

type Validated = {
  missionId: string;
  operator: string;
  targetChannel: string;
  audienceProfile: string;
  personaArchetype: string;
  personaNameSeed: string;
  artifactPrompt: string;
  dryRun: boolean;
};

async function validate(
  input: Input,
): Promise<{ ok: true; value: Validated } | { ok: false; error: string }> {
  const operator = (input.operator ?? "").trim() || "J2-INSCOM-Demo";
  const targetChannel = (input.targetChannel ?? "").trim();
  if (!targetChannel) return { ok: false, error: "Target channel is required." };

  // Channel must exist in the sandbox allowlist.
  let channels: Awaited<ReturnType<typeof listChannels>> = [];
  let channelLoadError: string | null = null;
  try {
    channels = await listChannels();
  } catch (e) {
    channelLoadError = (e as Error).message.slice(0, 200);
  }
  if (channelLoadError) {
    return {
      ok: false,
      error: `Could not load channel allowlist from Foundry: ${channelLoadError}`,
    };
  }
  const channel = channels.find(
    (c) =>
      c.channel_id === targetChannel ||
      c.displayName === targetChannel ||
      c.displayName === `@${targetChannel}`,
  );
  if (!channel) {
    return {
      ok: false,
      error: `Channel ${targetChannel} not in allowlist (${channels.length} channels loaded: ${channels.map((c) => c.channel_id).join(", ") || "none"}).`,
    };
  }
  if (!channel.isSandbox) {
    return {
      ok: false,
      error: `Channel ${channel.channel_id} is not a sandbox channel. Refused.`,
    };
  }

  const audienceProfile =
    (input.audienceProfile ?? "").trim() || channel.audienceProfile || "(unspecified)";

  const personaArchetype = (input.personaArchetype ?? "").trim();
  if (!personaArchetype)
    return { ok: false, error: "Persona archetype is required." };
  const personaNameSeed = (input.personaNameSeed ?? "").trim() || "Vlad K.";
  const artifactPrompt = (input.artifactPrompt ?? "").trim();
  if (!artifactPrompt) return { ok: false, error: "Artifact prompt is required." };

  // mission_id: operator-supplied or auto-generated SHADOW-FOX-<rand>
  let missionId = (input.missionId ?? "").trim();
  if (!missionId) {
    missionId = `SHADOW-FOX-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
  }
  if (!MID_RE.test(missionId)) {
    return {
      ok: false,
      error:
        "mission_id must match [A-Za-z0-9_-]+ (64 chars, must start alphanumeric).",
    };
  }

  // Sandbox enforcement: dry_run defaults to true. Operator must explicitly
  // pass dry_run=false to enable live delivery — and even then it requires
  // an environment variable to be set on the engine. We always force true
  // from this UI per PRODUCT.md.
  const dryRun = true;

  return {
    ok: true,
    value: {
      missionId,
      operator,
      targetChannel: channel.displayName || channel.channel_id,
      audienceProfile,
      personaArchetype,
      personaNameSeed,
      artifactPrompt,
      dryRun,
    },
  };
}

function escapeYamlString(s: string): string {
  // Quote and escape for YAML double-quoted scalar.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function renderSpec(v: Validated): string {
  return [
    `# Generated by Mendacity Operator Console at ${new Date().toISOString()}`,
    `# Schema: PALANTIR_BRIEF.md §4.1`,
    ``,
    `mission_id: ${v.missionId}`,
    `operator: ${escapeYamlString(v.operator)}`,
    ``,
    `authorization:`,
    `  authority: title-10`,
    `  target_class: foreign`,
    `  approval_chain:`,
    `    - "J2"`,
    `    - "OGC-reviewed"`,
    `    - "Operator"`,
    ``,
    `target:`,
    `  platform: telegram`,
    `  channel: ${escapeYamlString(v.targetChannel)}`,
    `  audience_profile: ${escapeYamlString(v.audienceProfile)}`,
    ``,
    `persona:`,
    `  archetype: ${escapeYamlString(v.personaArchetype)}`,
    `  name_seed: ${escapeYamlString(v.personaNameSeed)}`,
    `  generate_avatar: false`,
    ``,
    `artifact:`,
    `  type: image`,
    `  prompt: ${escapeYamlString(v.artifactPrompt)}`,
    `  must_pass:`,
    `    - c2pa`,
    `    - titan`,
    `    - synthid`,
    `  strip_watermarks: true`,
    ``,
    `delivery:`,
    `  schedule: immediate`,
    `  thread_strategy: cold_post`,
    `  dry_run: ${v.dryRun}`,
    ``,
  ].join("\n");
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  const valid = await validate(body as Input);
  if (!valid.ok) return Response.json({ error: valid.error }, { status: 400 });
  const v = valid.value;

  const yaml = renderSpec(v);

  await mkdir(INBOX, { recursive: true });
  const finalPath = path.join(INBOX, `${v.missionId}.yaml`);
  const tmpPath = `${finalPath}.tmp-${crypto.randomBytes(4).toString("hex")}`;

  try {
    await writeFile(tmpPath, yaml, { encoding: "utf-8", flag: "wx" });
    await rename(tmpPath, finalPath);
  } catch (e) {
    return Response.json(
      { error: `Could not write spec: ${(e as Error).message}` },
      { status: 500 },
    );
  }

  revalidatePath("/");
  revalidatePath("/audit");
  return Response.json({
    ok: true,
    missionId: v.missionId,
    inboxPath: finalPath,
    spec: v,
  });
}
