import "server-only";
import { mkdir, writeFile, rename } from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import { listChannels } from "@/lib/foundry";
import { listPersonas, type Persona } from "@/lib/personas";
import { insertCampaign, type DispatchPost } from "@/lib/campaigns";
import { revalidatePath } from "next/cache";

const REPO_ROOT = path.resolve(
  process.env.MENDACITY_REPO_ROOT ||
    path.join(process.env.HOME || "", "Mendacity"),
);
const INBOX = path.join(REPO_ROOT, "missions/inbox");

const MID_RE = /^[A-Za-z0-9][A-Za-z0-9_\-]{0,63}$/;

type Input = {
  missionId?: string;
  operator?: string;
  targetChannel?: string;
  audienceProfile?: string;
  seedPersonaId?: string;
  corroboratorPersonaIds?: string[];
  artifactPrompt?: string;
  dryRun?: boolean;
};

type Validated = {
  missionId: string;
  operator: string;
  targetChannel: string;
  audienceProfile: string;
  seedPersona: Persona;
  corroborators: Persona[];
  artifactPrompt: string;
  dryRun: boolean;
};

async function validate(
  input: Input,
): Promise<{ ok: true; value: Validated } | { ok: false; error: string }> {
  const operator = (input.operator ?? "").trim() || "J2-INSCOM-Demo";
  const targetChannel = (input.targetChannel ?? "").trim();
  if (!targetChannel) return { ok: false, error: "Target channel is required." };

  // Channel must exist in the sandbox allowlist.
  let channels: Awaited<ReturnType<typeof listChannels>> = [];
  let channelLoadError: string | null = null;
  try {
    channels = await listChannels();
  } catch (e) {
    channelLoadError = (e as Error).message.slice(0, 200);
  }
  if (channelLoadError) {
    return {
      ok: false,
      error: `Could not load channel allowlist from Foundry: ${channelLoadError}`,
    };
  }
  const channel = channels.find(
    (c) =>
      c.channel_id === targetChannel ||
      c.displayName === targetChannel ||
      c.displayName === `@${targetChannel}`,
  );
  if (!channel) {
    return {
      ok: false,
      error: `Channel ${targetChannel} not in allowlist (${channels.length} channels loaded: ${channels.map((c) => c.channel_id).join(", ") || "none"}).`,
    };
  }
  if (!channel.isSandbox) {
    return {
      ok: false,
      error: `Channel ${channel.channel_id} is not a sandbox channel. Refused.`,
    };
  }

  const audienceProfile =
    (input.audienceProfile ?? "").trim() || channel.audienceProfile || "(unspecified)";

  const seedPersonaId = (input.seedPersonaId ?? "").trim();
  if (!seedPersonaId) return { ok: false, error: "Seed persona is required." };
  const allPersonas = await listPersonas();
  const personasById = new Map(allPersonas.map((p) => [p.id, p]));
  const seedPersona = personasById.get(seedPersonaId);
  if (!seedPersona)
    return { ok: false, error: `Seed persona ${seedPersonaId} not found.` };

  const requestedCorroborators = Array.isArray(input.corroboratorPersonaIds)
    ? input.corroboratorPersonaIds
    : seedPersona.knows;
  const corroborators: Persona[] = [];
  const seenIds = new Set<string>([seedPersona.id]);
  for (const cid of requestedCorroborators) {
    if (seenIds.has(cid)) continue;
    const p = personasById.get(cid);
    if (!p) continue;
    corroborators.push(p);
    seenIds.add(cid);
  }

  const artifactPrompt = (input.artifactPrompt ?? "").trim();
  if (!artifactPrompt) return { ok: false, error: "Artifact prompt is required." };

  // mission_id: operator-supplied or auto-generated SHADOW-FOX-<rand>
  let missionId = (input.missionId ?? "").trim();
  if (!missionId) {
    missionId = `SHADOW-FOX-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
  }
  if (!MID_RE.test(missionId)) {
    return {
      ok: false,
      error:
        "mission_id must match [A-Za-z0-9_-]+ (64 chars, must start alphanumeric).",
    };
  }

  // Sandbox enforcement: dry_run defaults to true. Operator must explicitly
  // pass dry_run=false to enable live delivery — and even then it requires
  // an environment variable to be set on the engine. We always force true
  // from this UI per PRODUCT.md.
  const dryRun = true;

  return {
    ok: true,
    value: {
      missionId,
      operator,
      targetChannel: channel.displayName || channel.channel_id,
      audienceProfile,
      seedPersona,
      corroborators,
      artifactPrompt,
      dryRun,
    },
  };
}

function escapeYamlString(s: string): string {
  // Quote and escape for YAML double-quoted scalar.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

function renderSpec(v: Validated): string {
  const corrLines = v.corroborators.length
    ? v.corroborators.map((p) => `    - ${escapeYamlString(p.id)}`)
    : [`    []`];
  return [
    `# Generated by Mendacity Operator Console at ${new Date().toISOString()}`,
    `# Schema: PALANTIR_BRIEF.md §4.1`,
    ``,
    `mission_id: ${v.missionId}`,
    `operator: ${escapeYamlString(v.operator)}`,
    ``,
    `authorization:`,
    `  authority: title-10`,
    `  target_class: foreign`,
    `  approval_chain:`,
    `    - "J2"`,
    `    - "OGC-reviewed"`,
    `    - "Operator"`,
    ``,
    `target:`,
    `  platform: telegram`,
    `  channel: ${escapeYamlString(v.targetChannel)}`,
    `  audience_profile: ${escapeYamlString(v.audienceProfile)}`,
    ``,
    `persona:`,
    `  seed_id: ${escapeYamlString(v.seedPersona.id)}`,
    `  seed_name: ${escapeYamlString(v.seedPersona.name)}`,
    `  language: ${escapeYamlString(v.seedPersona.language)}`,
    `  geo_anchor: ${escapeYamlString(v.seedPersona.geoAnchor)}`,
    ``,
    `corroborators:`,
    ...corrLines,
    ``,
    `artifact:`,
    `  type: image`,
    `  prompt: ${escapeYamlString(v.artifactPrompt)}`,
    `  must_pass:`,
    `    - c2pa`,
    `    - titan`,
    `    - synthid`,
    `  strip_watermarks: true`,
    ``,
    `delivery:`,
    `  schedule: immediate`,
    `  thread_strategy: cold_post`,
    `  dry_run: ${v.dryRun}`,
    ``,
  ].join("\n");
}

function pickFlavor(persona: Persona): string {
  if (persona.examples.length === 0) {
    return `(${persona.name} writes about the situation)`;
  }
  return persona.examples[Math.floor(Math.random() * persona.examples.length)];
}

function seedPostText(persona: Persona, prompt: string): string {
  const flavor = pickFlavor(persona);
  return `${flavor}\n\n[image attached — ${prompt}]`;
}

function corroboratorPostText(
  persona: Persona,
  seedName: string,
): string {
  const flavor = pickFlavor(persona);
  return `${flavor}\n\n(picked up via ${seedName})`;
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  const valid = await validate(body as Input);
  if (!valid.ok) return Response.json({ error: valid.error }, { status: 400 });
  const v = valid.value;

  const yaml = renderSpec(v);

  await mkdir(INBOX, { recursive: true });
  const finalPath = path.join(INBOX, `${v.missionId}.yaml`);
  const tmpPath = `${finalPath}.tmp-${crypto.randomBytes(4).toString("hex")}`;

  try {
    await writeFile(tmpPath, yaml, { encoding: "utf-8", flag: "wx" });
    await rename(tmpPath, finalPath);
  } catch (e) {
    return Response.json(
      { error: `Could not write spec: ${(e as Error).message}` },
      { status: 500 },
    );
  }

  // Spin up the corresponding social-media attack chain. Seed posts
  // immediately; corroborators are scheduled with a stagger so the timeline
  // visibly progresses.
  const campaignId = `c_${v.missionId}`;
  const delayRange: [number, number] = [45, 180];
  const now = Date.now();
  const posts: DispatchPost[] = [];
  const roster: Record<string, "seed" | "corroborator"> = {};

  posts.push({
    id: `p_${crypto.randomBytes(4).toString("hex")}`,
    personaId: v.seedPersona.id,
    role: "seed",
    generatedContent: seedPostText(v.seedPersona, v.artifactPrompt),
    postedAt: new Date(now).toISOString(),
    status: "posted",
  });
  roster[v.seedPersona.id] = "seed";

  for (let i = 0; i < v.corroborators.length; i++) {
    const c = v.corroborators[i];
    const cumulative = Array.from({ length: i + 1 }, () =>
      delayRange[0] +
      Math.random() * (delayRange[1] - delayRange[0]),
    ).reduce((a, b) => a + b, 0);
    posts.push({
      id: `p_${crypto.randomBytes(4).toString("hex")}`,
      personaId: c.id,
      role: "corroborator",
      generatedContent: corroboratorPostText(c, v.seedPersona.name),
      postedAt: new Date(now + cumulative * 1000).toISOString(),
      status: "pending_approval",
    });
    roster[c.id] = "corroborator";
  }

  let campaignError: string | null = null;
  try {
    await insertCampaign({
      id: campaignId,
      intent: v.artifactPrompt,
      channel: v.targetChannel,
      status: "running",
      createdBy: v.operator,
      delayRangeSeconds: delayRange,
      roster,
      posts,
    });
  } catch (e) {
    campaignError = (e as Error).message.slice(0, 300);
  }

  revalidatePath("/");
  revalidatePath("/audit");
  revalidatePath("/backstop");
  revalidatePath("/personas");
  return Response.json({
    ok: true,
    missionId: v.missionId,
    campaignId,
    inboxPath: finalPath,
    spec: v,
    campaignError,
  });
}
