[theme]
base = "light"
primaryColor = "#16140F"
backgroundColor = "#F1ECE0"
secondaryBackgroundColor = "#E6E0D0"
textColor = "#16140F"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
